Models/CRUDs/Subasta.cs
using SubIn.Models;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.IO;

namespace SubIn.Models
{
    public class Subasta : Conexion
    {
        public int id_subasta { get; set; } // 
        public string title { get; set; } // 
        public DateTime fecha { get; set; }  // 
        public string descripcion_subasta { get; set; }
        public byte[] img_subasta { get; set; }



        public Subasta()
        {
        }

        public Subasta(int id_subasta, string title, DateTime fecha, string descripcion_subasta, byte[] img_subasta) //
        {
            this.id_subasta = id_subasta; //
            this.title = title;
            this.fecha = fecha; //
            this.descripcion_subasta = descripcion_subasta;
            this.img_subasta = img_subasta;
        }

 
        public List<Subasta> GetSubasta()
        {
            List<Subasta> lista = new List<Subasta>();
            const string SQL = "SELECT * FROM Subasta;";
            DataTable tabla = GetQuery(SQL);
            foreach (DataRow row in tabla.Rows)
            {
                lista.Add(new Subasta((int)row["id_subasta"], (string)row["title"], (DateTime)row["fecha"], (string)row["descripcion_subasta"], (byte[])row["img_subasta"]));
            }
            return lista;
        }

        public bool AddSubasta(Subasta subastita)
        {

                const string SQL = "INSERT INTO Subasta(title, fecha, descripcion_subasta, img_subasta) VALUES(:title, :nombre, :desc, :img);";
                NpgsqlParameter paramIdSub = new NpgsqlParameter(":title", subastita.title);
                NpgsqlParameter paramFecha = new NpgsqlParameter(":nombre", subastita.fecha);
                NpgsqlParameter paramDesc = new NpgsqlParameter(":desc", subastita.descripcion_subasta);
                NpgsqlParameter paramImg = new NpgsqlParameter(":img", subastita.img_subasta);
                List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { paramIdSub, paramFecha, paramDesc, paramImg };

                return GetQuery(SQL, lista).Rows.Count > 0;
            

            
        }

        public void DeleteSubasta(Subasta subastita)
        {
            const string SQL = "DELETE from subasta where id_subasta=:id";
            List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { new NpgsqlParameter(":id", subastita.id_subasta) };
            GetQuery(SQL, lista);

        }

        public Subasta ObtenerSubastaById(int id)
        {
            const string SQL = "SELECT * FROM Subasta WHERE id_subasta=:id";
            List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { new NpgsqlParameter(":id", id) };
            DataTable tabla = GetQuery(SQL, lista);
            if (tabla.Rows.Count <= 0) return new Subasta();
            DataRow row = tabla.Rows[0];
            return new Subasta((int)row["id_subasta"], (string)row["title"],(DateTime)row["fecha"], (string)row["descripcion_subasta"], (byte[])row["img_subasta"]);
        }

        public void UpdateSubasta(Subasta subastita)
        {
            const string SQL = "UPDATE Categoria set title = :title, fecha = :fecha, descripcion_subasta = :desc, img_subasta = :img WHERE id_subasta = :subasta";
            NpgsqlParameter paramIdSub = new NpgsqlParameter(":subasta", subastita.id_subasta);
            NpgsqlParameter paramTitle = new NpgsqlParameter(":title", subastita.title);
            NpgsqlParameter paramFecha = new NpgsqlParameter(":fecha", subastita.fecha);
            NpgsqlParameter paramDesc = new NpgsqlParameter(":desc", subastita.descripcion_subasta);
            NpgsqlParameter paramImg = new NpgsqlParameter(":img", subastita.img_subasta);
            List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { paramTitle, paramFecha, paramDesc, paramImg, paramIdSub };
            GetQuery(SQL, lista);
        }
    }
}

Controllers/PagoPayPalController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using SubIn.Models.Paypal_Order;
using SubIn.Models.Paypal_Transaction;

namespace SubIn.Controllers
{
    public class PagoPayPalController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> About()
        {

            //id de la autorizacion para obtener el dinero
            string token = Request.QueryString["token"];

            bool status = false;


            using (var client = new HttpClient())
            {

                //INGRESA TUS CREDENCIALES AQUI -> CLIENT ID - SECRET
                var userName = "AR1TLcUGoV-g-Tx6AN_k0tZIUNzC5HyKX0bbpzg3kBffokpdmX96GSRdFuAsdecoCB5tehb2MWgQsAFj";
                var passwd = "EP_I3fA9pGd-dxvLiHUyPCPcjrkvnocRkhlyhk8mz2cwuN0kRuSY466Lh8TLdtRwTcusEk536mHYsktd";

                client.BaseAddress = new Uri("https://api-m.sandbox.paypal.com");

                var authToken = Encoding.ASCII.GetBytes($"{userName}:{passwd}");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(authToken));

                var data = new StringContent("{}", Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PostAsync($"/v2/checkout/orders/{token}/capture", data);


                status = response.IsSuccessStatusCode;

                ViewData["Status"] = status;
                if (status)
                {
                    var jsonRespuesta = response.Content.ReadAsStringAsync().Result;

                    PaypalTransaction objeto = JsonConvert.DeserializeObject<PaypalTransaction>(jsonRespuesta);

                    ViewData["IdTransaccion"] = objeto.purchase_units[0].payments.captures[0].id;
                }

            }


            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpPost]
        //public JsonResult Paypal(string precio) ---> EDITAR POR LA LINEA DE ABAJO
        public async Task<JsonResult> Paypal(string precio, string producto)
        {



            bool status = false;
            string respuesta = string.Empty;

            using (var client = new HttpClient())
            {

                //INGRESA TUS CREDENCIALES AQUI -> CLIENT ID - SECRET
                var userName = "AR1TLcUGoV-g-Tx6AN_k0tZIUNzC5HyKX0bbpzg3kBffokpdmX96GSRdFuAsdecoCB5tehb2MWgQsAFj";
                var passwd = "EP_I3fA9pGd-dxvLiHUyPCPcjrkvnocRkhlyhk8mz2cwuN0kRuSY466Lh8TLdtRwTcusEk536mHYsktd";

                client.BaseAddress = new Uri("https://api-m.sandbox.paypal.com");

                var authToken = Encoding.ASCII.GetBytes($"{userName}:{passwd}");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(authToken));


                var orden = new PaypalOrder()
                {
                    intent = "CAPTURE",
                    purchase_units = new List<Models.Paypal_Order.PurchaseUnit>() {

                        new Models.Paypal_Order.PurchaseUnit() {

                            amount = new Models.Paypal_Order.Amount() {
                                currency_code = "USD",
                                value = precio
                            },
                            description = producto
                        }
                    },
                    application_context = new ApplicationContext()
                    {
                        brand_name = "Mi Tienda",
                        landing_page = "NO_PREFERENCE",
                        user_action = "PAY_NOW", //Accion para que paypal muestre el monto de pago
                        return_url = "https://localhost:44321/Home/About",// cuando se aprovo la solicitud del cobro
                        cancel_url = "https://localhost:44321/Home/Index"// cuando cancela la operacion
                    }
                };


                var json = JsonConvert.SerializeObject(orden);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PostAsync("/v2/checkout/orders", data);


                status = response.IsSuccessStatusCode;


                if (status)
                {
                    respuesta = response.Content.ReadAsStringAsync().Result;
                }



            }

            return Json(new { status = status, respuesta = respuesta }, JsonRequestBehavior.AllowGet);

        }
    }
}

Controllers/SubastaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SubIn.Models;
using System.Web.Mvc;
using System.Web;
using System.Web.Helpers;

namespace SubIn.Controllers
{
    public class SubastaController : Controller
    {
        // GET: SubastaController
        public ActionResult Index()
        {
            //byte[] imageData = ObtenerImagenDesdeBD();
            //ViewBag.Imagen = imageData;

            return View(new Subasta().GetSubasta());
        }

        // GET: SubastaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SubastaController/Create
        public ActionResult Create()
        {
            return View(new Subasta());
        }

        // POST: SubastaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection formcollection, Subasta subastita)
        {
            HttpPostedFileBase FileBase = Request.Files[0];

            WebImage image = new WebImage(FileBase.InputStream);

            subastita.img_subasta = image.GetBytes();

            try
            {
                subastita.AddSubasta(subastita);
                return View(subastita);
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return View(subastita);
            }
        }

        // GET: SubastaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(new Subasta().ObtenerSubastaById(id));
        }

        // POST: SubastaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FormCollection collection, Subasta subastita)
        {
            try
            {
                subastita.UpdateSubasta(subastita);
                return View("Index", new Subasta().GetSubasta());
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return View();
            }
        }

        // GET: SubastaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(new Subasta().ObtenerSubastaById(id));
        }

        // POST: SubastaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection collection, Subasta subastita)
        {
            try
            {
                subastita.DeleteSubasta(subastita); return View("Index");
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return View("Index");
            }
        }
    }
}

Views/Subasta/Create.cshtml
@model SubIn.Models.Subasta

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container page-container">
    <h2>Crear</h2>

    @using (Html.BeginForm("Create", "Subasta", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Subasta</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                    @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.descripcion_subasta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion_subasta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion_subasta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.img_subasta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @*@Html.TextBoxFor(model => model.img_subasta, new { type = "file" })*@
                    <input type="file" name="imageload" />
                    @Html.ValidationMessageFor(model => model.img_subasta, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>

Views/Subasta/Index.cshtml
@model IEnumerable<SubIn.Models.Subasta>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<main class="container">
    <div class="container__title">
        <h2>
            Subastas
        </h2>
    </div>
    
    <div class="container__crear" style="margin-bottom: 50px;">
        @Html.ActionLink("Crear Subasta", "Create", "Subasta", new { area = "" }, new { @class = "btn btn-primary" })
    </div>

    <div class="d-flex flex-wrap justify-content-between">
        @foreach (var item in Model)
        {
            <div class="section__card_subasta card" style="width: 18rem; margin-bottom: 20px; height: 500px;">

                <img src="data:image;base64,@System.Convert.ToBase64String(item.img_subasta)" alt="Imagen subasta" class="img__subasta card-img-top">

                <div class="container__body">
                    <h3 class="title__subasta card-title">@Html.DisplayFor(modelItem => item.title)</h3>
                    <h5 class="subtitle__subasta card-subtitle">@Html.DisplayFor(modelItem => item.fecha)</h5>
                    <p class="descripcion__subasta card-text">
                        @Html.DisplayFor(modelItem => item.descripcion_subasta)
                    </p>

                    @Html.ActionLink("Ver Subasta", "Index", "PagoPayPal", new { area = "" }, new { @class = "btn btn-dark" })
                </div>

            </div>
        } 
    </div>
</main>




@*<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.id_subasta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.id_item)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.id_subasta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecha)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.id_item)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>*@