Models/CRUDs/Usuario.cs
using SubIn.Models;
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace SubIn.Models
{
    public class Usuario : Conexion
    {
        public int id_usuario { get; set; } //
        public string nombre { get; set; } // 
        public string apellidos { get; set; } // declaramos variable publicas para toda la clase
        public string email { get; set; } //
        public string contrasena { get; set; } //
        public Int64 telefono { get; set; } //

        public Usuario() // El contructor vacio 
        {
        }

        public Usuario(int id_usuario, string nombre, string apellidos, string email, string contrasena, Int64 telefono) //
        {
            this.id_usuario = id_usuario; //
            this.nombre = nombre; //
            this.apellidos = apellidos; // Declaramos el constructor de la clase usando paso de parmetros y las variable publicas previamente declaradas
            this.email = email; //
            this.contrasena = contrasena;
            this.telefono = telefono; //
        }


        public List<Usuario> GetUsuario()
        {
            List<Usuario> lista = new List<Usuario>();
            const string SQL = "SELECT * FROM Usuario;";
            DataTable tabla = GetQuery(SQL);  // Funcion que obtiene los.usjarios registrados en la.base de datos de la.tabala usuarios
            foreach (DataRow row in tabla.Rows)
            {
                lista.Add(new Usuario((int)row["id_usuario"], (string)row["nombre"], (string)row["apellidos"], (string)row["email"], (string)row["contrasena"], (Int64)row["telefono"])); // la listade parametros que se mostraran en ka.vista
            }
            return lista;
        }

        public int GetUsuarioForLogin(string email, string contrasena)
        {
            const string SQL = "SELECT * FROM usuario WHERE email=:email and contrasena=:contrasena";
            NpgsqlParameter paramEmail = new NpgsqlParameter(":email", email);
            NpgsqlParameter paramContra = new NpgsqlParameter(":contrasena", contrasena);
            List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { paramEmail, paramContra };
            DataTable tabla = GetQuery(SQL, lista);
            DataRow row = tabla.Rows[0];
            return (int)row["id_usuario"]; // devuelve la informacion del registro obtenido por id 

        }

        public bool AddUsuario(Usuario usuarito) // Funcion que permite añandir registro dentro de la tabla usuarios
        {
            const string SQL = "INSERT INTO usuario(nombre, apellidos, email, contrasena, telefono) VALUES(:nom, :ap, :email, :contrasena, :telefono);";
            NpgsqlParameter paramNombre = new NpgsqlParameter(":nom", usuarito.nombre);
            NpgsqlParameter paramAp = new NpgsqlParameter(":ap", usuarito.apellidos);
            NpgsqlParameter paramEmail = new NpgsqlParameter(":email", usuarito.email);
            NpgsqlParameter paramContra = new NpgsqlParameter(":contrasena", usuarito.contrasena);
            NpgsqlParameter paramTelefono = new NpgsqlParameter(":telefono", usuarito.telefono);
            List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { paramNombre, paramAp, paramEmail, paramContra, paramTelefono };

            return GetQuery(SQL, lista).Rows.Count > 0; // Gracias alos parametros previamente declaras y añadidos a la conaulta regustra al usuario con una funcion usando el metodo de la clase conexion
        }

        public void DeletePersona(Usuario usuarito) // Funcion que permite borrar registros de la tabla usuarios
        {
            const string SQL = "DELETE from usuario where id_usuario=:id";
            List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { new NpgsqlParameter(":id", usuarito.id_usuario) };
            GetQuery(SQL, lista); // Ejecuta la conaulta dentro de posrgres donde se borra el.registro a partir del.id

        }

        public Usuario ObtenerUsuarioById(int id) // funcion que se dedica a obtener informacion de un registro por medio del.id 
        {
            const string SQL = "SELECT * FROM usuario WHERE id_usuario=:id";
            List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { new NpgsqlParameter(":id", id) };
            DataTable tabla = GetQuery(SQL, lista);
            if (tabla.Rows.Count <= 0) return new Usuario();
            DataRow row = tabla.Rows[0];
            return new Usuario((int)row["id_usuario"], (string)row["nombre"], (string)row["apellidos"], (string)row["email"], (string)row["contrasena"], (Int64)row["telefono"]); // devuelve la informacion del registro obtenido por id 
        }

        public void UpdateUsuario(Usuario usuarito) // Funcion que se encarga de actualizar los datos, dandole.todos los dstoa por psrameteo en la co sukta
        {
            const string SQL = "UPDATE usuario set nombre = :nom, apellidos = :ap, email = :email, telefono = :telefono WHERE id_usuario = :id";

            NpgsqlParameter paramNom = new NpgsqlParameter(":nom", usuarito.nombre);
            NpgsqlParameter paramAp = new NpgsqlParameter(":ap", usuarito.apellidos);
            NpgsqlParameter paramEmail = new NpgsqlParameter(":curp", usuarito.email);
            NpgsqlParameter paramTelefono = new NpgsqlParameter(":telefono", usuarito.telefono);
            NpgsqlParameter paramId = new NpgsqlParameter(":id", usuarito.id_usuario);

            List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { paramNom, paramAp, paramEmail, paramTelefono, paramId };
            GetQuery(SQL, lista);
        }

    }


   
}

Models/Login/Login.cs
using Npgsql;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace SubIn.Models.Login
{
    public class Login : Conexion
    {


        public Usuario getUserByEmailPass(string correo, string contrasena)
        {
            const string SQL = "SELECT * FROM usuario WHERE email=:email and contrasena = :contrasena";
            NpgsqlParameter paramCorreo = new NpgsqlParameter(":email", correo);
            NpgsqlParameter paramContrasena = new NpgsqlParameter(":contrasena", contrasena);
            List<NpgsqlParameter> lista = new List<NpgsqlParameter>() { paramCorreo, paramContrasena };
            DataTable tabla = GetQuery(SQL, lista);
            if (tabla.Rows.Count <= 0) return new Usuario();
            DataRow row = tabla.Rows[0];
            return new Usuario((int)row["id_usuario"], (string)row["nombre"], (string)row["apellidos"], (string)row["email"], (string)row["contrasena"], (Int64)row["telefono"]); // devuelve la informacion del registro obtenido por id 

        }


    }
}

Controllers/IntercambioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SubIn.Models;
using System.Web.Mvc;
using System.Web;

namespace SubIn.Controllers
{
    public class IntercambioController : Controller
    {
        // GET: IntercambioController
        public ActionResult Index(int id)
        {
            HttpCookie cookie = new HttpCookie("id", id.ToString());
            Response.Cookies.Add(cookie);
            return View(new Item().GetInventario(id));
        }

        // GET: IntercambioController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: IntercambioController/Create
        public ActionResult Create()
        {
            return View(new Intercambio());
        }

        // POST: IntercambioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection collection, Intercambio intercambiocito)
        {
            try
            {
                HttpCookie IdItem2Cookie = new HttpCookie("id_item2", intercambiocito.id_item2.ToString());
                HttpCookie IdUsuarioCookie = new HttpCookie("id_item2", intercambiocito.id_usuario.ToString());
                
                
                Response.Cookies.Add(IdItem2Cookie);
                Response.Cookies.Add(IdUsuarioCookie);

                intercambiocito.AddIntercambio(intercambiocito);
                return View(intercambiocito);
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return View(intercambiocito);
            }
        }

        // GET: IntercambioController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(new Intercambio().ObtenerIntercambioById(id));
        }

        // POST: IntercambioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FormCollection collection, Intercambio intercambiocito)
        {
            try
            {
                intercambiocito.UpdateIntercambio(intercambiocito);
                return View("Index", new Intercambio().GetIntercambio());
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return View();
            }
        }

        // GET: IntercambioController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(new Intercambio().ObtenerIntercambioById(id));
        }

        // POST: IntercambioController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection collection, Intercambio intercambiocito)
        {
            try
            {
                intercambiocito.DeleteIntercambio(intercambiocito); return View("Index");
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return View("Index");
            }
        }
    }
}

Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using SubIn.Models;

namespace SubIn.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: UsuarioController
        public ActionResult Index()
        {
            return View(new Usuario().GetUsuario());
        }

        // GET: UsuarioController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UsuarioController/Create
        public ActionResult Register()
        {
            return View(new Usuario());
        }

        // POST: UsuarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(FormCollection formcollection, Usuario usuarito)
        {
            try
            {
                usuarito.AddUsuario(usuarito);
                return View(usuarito);
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return View(usuarito);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email, string password)
        {
            // Validar las credenciales del usuario...
            int usuarito = new Usuario().GetUsuarioForLogin(email, password);



            // Si las credenciales son válidas, guardar el id del usuario en la sesión
            Session["id_usuario"] = usuarito;

            // Redirigir a la página principal
            return RedirectToAction("Index", "Home");
        }

        // GET: UsuarioController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(new Usuario().ObtenerUsuarioById(id));
        }

        // POST: UsuarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FormCollection collection, Usuario usuarito)
        {
            try
            {
                usuarito.UpdateUsuario(usuarito);
                return View("Index", new Usuario().GetUsuario());
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return View();
            }
        }

        // GET: UsuarioController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(new Usuario().ObtenerUsuarioById(id));
        }

        // POST: UsuarioController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection collection, Usuario usuarito)
        {
            try
            {
                usuarito.DeletePersona(usuarito); return View("Index");
            }
            catch (Exception e)
            {
                string msg = e.Message;
                return View("Index");
            }
        }
    }
}

Views/Usuario/Index.cshtml
@model IEnumerable<SubIn.Models.Usuario>

@{
    ViewBag.Title = "Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Intercambio</h2>


    <table class="table">
        <tr>
            <th>
                ID
            </th>
            <th>
                Nombre
            </th>
            <th>
                Apellidos
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id_usuario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.apellidos)
                </td>
                <td>
                    @using (Html.BeginForm("Index", "Intercambio", FormMethod.Get, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <input type="hidden" value="@Html.DisplayFor(modelItem => item.id_usuario)" name="id" />
                        <div class="form-actions no-color">
                            <input type="submit" value="Ver Inventario" class="btn btn-outline-dark" /> 
                        </div>
                    }
                    @*@Html.ActionLink("Ver Inventario", "Index", "Intercambio", new { area = "" }, new { id = item.id_usuario })*@
                </td>
            </tr>
        }

    </table>

</div>

Views/Usuario/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>

Views/Usuario/Register.cshtml
@model SubIn.Models.Usuario

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Create</h2>

    @using (Html.BeginForm("Register", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Usuario</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.apellidos, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.apellidos, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.contrasena, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.contrasena, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.contrasena, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Register" class="btn btn-dark" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index", "Home")
    </div>

</div>